name: Checks
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Cache:
    runs-on: ubuntu-latest
    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.10.1
        with:
          all_but_latest: true
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 12.x
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: 12.x
          registry-url: https://npm.pkg.github.com/

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm i

      - name: Cache dependencies
        id: initial-cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

  TSC:
    runs-on: ubuntu-latest
    needs: Cache
    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.10.1
        with:
          all_but_latest: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 12.x
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: 12.x
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm i

      - name: Cache dependencies
        id: tsc-cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: TSC
        run: npm run tsc

  TEST:
    runs-on: ubuntu-latest
    needs: Cache
    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.10.1
        with:
          all_but_latest: true
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 12.x
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: 12.x
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm i

      - name: Cache dependencies
        id: test-cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: test
        run: npm run test
